/***********************************************************************/
/*                                                                     */
/*  FILE        :dbsct.c                                               */
/*  DATE        :Sat, Jul 12, 2008                                     */
/*  DESCRIPTION :Setting of B,R Section                                */
/*  CPU TYPE    :Other                                                 */
/*                                                                     */
/*  This file is generated by Renesas Project Generator (Ver.4.5).     */
/*                                                                     */
/***********************************************************************/
                  


#pragma section $DSEC
static const struct {
	char *rom_s;       /* 初期化データセクションのROM 上の先頭アドレス */
	char *rom_e;       /* 初期化データセクションのROM 上の最終アドレス */
	char *ram_s;       /* 初期化データセクションのRAM 上の先頭アドレス */
}DTBL[]= {__sectop("D"), __secend("D"), __sectop("R")};
#pragma section $BSEC
static const struct {
	char *b_s;         /* 未初期化データセクションの先頭アドレス */
	char *b_e;         /* 未初期化データセクションの最終アドレス */
}BTBL[]= {__sectop("B"), __secend("B")};
